// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace eMBEDAutomationTests.Features.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ValidateEmbedDashboardPageFeatures")]
    [NUnit.Framework.CategoryAttribute("embedsmoketest")]
    public partial class ValidateEmbedDashboardPageFeaturesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ValidateEmbedDashboardPageFeatures.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ValidateEmbedDashboardPageFeatures", "\tThis sanity test is to ensure the state of Dashboard page elements and ensure al" +
                    "l links, panels, etc. \r\n\tare present and work as expected, before the main testi" +
                    "ng takes place", ProgrammingLanguage.CSharp, new string[] {
                        "embedsmoketest"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("I am logged into eMBED and viewing the Dashboard page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A top navigation section provides links to CIM, account and view settings")]
        public virtual void ATopNavigationSectionProvidesLinksToCIMAccountAndViewSettings()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A top navigation section provides links to CIM, account and view settings", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 10
 testRunner.Given("the top navigation elements have loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "topLink",
                        "expectedLocation"});
            table1.AddRow(new string[] {
                        "Logo",
                        "http://testing05/"});
            table1.AddRow(new string[] {
                        "CIM",
                        "http://testing05:50000/mbed"});
            table1.AddRow(new string[] {
                        "UserName",
                        "http://testing05/profile/mcrowther"});
            table1.AddRow(new string[] {
                        "SignOut",
                        "http://testing05/users/account/logoff"});
            table1.AddRow(new string[] {
                        "OrgSelector",
                        "org-selector"});
#line 11
 testRunner.Then("each <topLink> goes to the <expectedLocation>", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A Filter element allows users to select month and year range for analysis")]
        public virtual void AFilterElementAllowsUsersToSelectMonthAndYearRangeForAnalysis()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A Filter element allows users to select month and year range for analysis", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 21
 testRunner.Given("I have clicked on the filter burger icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
 testRunner.When("I select a month and year range", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.Then("the data returned matches the date range selected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A set of navigation links are shown that take the user to relevent dashboard sect" +
            "ions")]
        public virtual void ASetOfNavigationLinksAreShownThatTakeTheUserToReleventDashboardSections()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A set of navigation links are shown that take the user to relevent dashboard sect" +
                    "ions", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 26
 testRunner.Given("the navigation elements are present on the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 27
 testRunner.And("the SAR <item> is active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("each other <item> is present and inactive but selectable", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "item",
                        "navLocation"});
            table2.AddRow(new string[] {
                        "SAR",
                        "http://testing05:50000/mbed#/performance"});
            table2.AddRow(new string[] {
                        "RiskStrat",
                        "http://testing05:50000/mbed#/riskstratification"});
            table2.AddRow(new string[] {
                        "GPOS",
                        "http://testing05:50000/mbed#/gpos"});
            table2.AddRow(new string[] {
                        "Performance",
                        "http://testing05:50000/mbed/performance"});
#line 29
 testRunner.Then("they link to the expected <navLocation>", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Secondary Care Indicators panel can be expanded to view SAR by ACS and by Diagnos" +
            "is data")]
        public virtual void SecondaryCareIndicatorsPanelCanBeExpandedToViewSARByACSAndByDiagnosisData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Secondary Care Indicators panel can be expanded to view SAR by ACS and by Diagnos" +
                    "is data", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 37
 testRunner.Given("I have expanded the Secondary Care Indicators panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 38
 testRunner.And("I can see the SAR by ACS and by Diagnosis sections", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.Then("I can expand both of these to view the data in each panel section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A user can export the information on the dashboard to PDF")]
        public virtual void AUserCanExportTheInformationOnTheDashboardToPDF()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A user can export the information on the dashboard to PDF", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 42
 testRunner.Given("I have selected the Export to PDF tool icon in a <panel>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
 testRunner.When("a PDF file save dialogue is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "panel"});
            table3.AddRow(new string[] {
                        "Secondary"});
            table3.AddRow(new string[] {
                        "byACS"});
            table3.AddRow(new string[] {
                        "byDiagnosis"});
#line 44
 testRunner.Then("I can save the PDF and get returned to the main screen", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer text provides required copyright notices and reference links")]
        public virtual void FooterTextProvidesRequiredCopyrightNoticesAndReferenceLinks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer text provides required copyright notices and reference links", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 52
 testRunner.Given("the footer has copyright notices and reference links", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
 testRunner.Then("the copyright notices should state the current year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "linkText",
                        "linkLocation"});
            table4.AddRow(new string[] {
                        "My DR Foster",
                        "http://testing05:50000/"});
            table4.AddRow(new string[] {
                        "Feedback",
                        "OpenUserVoiceDialogue"});
#line 54
 testRunner.And("reference links should go to the correct locations", ((string)(null)), table4, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
